version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202104-01
    resource_class: large
    steps:
      - checkout
      #- run: dd if=/dev/zero of=swapfile bs=1M count=8192 status=progress && sudo chown root:disk swapfile && sudo chmod 600 swapfile && sudo mkswap swapfile && sudo swapon swapfile
      #- run: sudo apt install bc bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      - run: free -h
      - run: git config --global user.email "tukaiari@gmail.com"
      - run: git config --global user.name "Arijit Roy"
      - run: sudo apt update && sudo apt install bc wget bison build-essential ccache curl flex g++-multilib gcc-multilib git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev
      - run: PATH=~/bin:$PATH && curl https://storage.googleapis.com/git-repo-downloads/repo > ~/bin/repo && chmod a+x ~/bin/repo
      - run: mkdir posp && cd posp && repo init --depth=1 -u https://github.com/PotatoProject/manifest -b frico_mr1-release
      - run: cd posp && repo sync
      #- run: cd actions-runner && curl -o actions-runner-linux-x64-2.286.1.tar.gz -L https://github.com/actions/runner/releases/download/v2.286.1/actions-runner-linux-x64-2.286.1.tar.gz && echo "7b1509c353ea4e6561b2ed2e916dcbf2a0d8ce21172edd9f8c846a20b6462cd6  actions-runner-linux-x64-2.286.1.tar.gz" | shasum -a 256 -c && tar xzf ./actions-runner-linux-x64-2.286.1.tar.gz
      #- run: cd actions-runner && echo -en "\n\n\n\n" | ./config.sh --url https://github.com/arijit192/cci --token ADVKAGBJBAXPY6LTB3STRLDB5SDWA && ./run.sh
      - run:
          command: cd posp && source build/envsetup.sh && lunch potato_alioth-userdebug && brunch alioth
          no_output_timeout: 2h 
